#!/usr/bin/env python
import base64
import urllib2
from json import loads
from urlparse import urljoin
from itertools import imap
from subprocess import Popen
from sys import argv, exit
from time import sleep


def get_jobs(config):
    def make_job(job):
        return {'url': job.get('url'),
                'name': job.get('name')}

    jobs = ask(config['jenkins url'])
    if config.get('jobs'):
        jobs = [job for job in jobs['jobs']
                if job.get('name') in config['jobs']]
    else:
        jobs = jobs['jobs']
    return imap(make_job, jobs)


def jobs_running_info(jobs):
    def make_job(job):
        return job.get('name'), running(job)
    return dict(make_job(job) for job in jobs)


def running(job):
    status = get_job_status(job)

    build = get_last_build(status)
    if build:
        build_info = ask(build.get('url'))
        if build_info.get('building'):
            return "RUNNING"
        return build_info.get('result')
    return "UNKNOWN"


def get_job_status(job):
    # Current upstream jenkins have bug
    # https://issues.jenkins-ci.org/browse/JENKINS-15713
    # so, running builds can only be acquired with this ugly workarounc
    try:
        url = urljoin(job.get('url'), 'api/json')
        url += '?tree=allBuilds[name,url,result,building,number]'
        r = urllib2.urlopen(url).read()
        return {'builds': loads(r)['allBuilds']}
    except (ValueError, urllib2.URLError):
        print "Ignoring invalid job status info at url %s" % url
    return {}


def get_last_build(job_status):
    def compare(job1, job2):
        return job1.get('number') < job2.get('number')

    builds = job_status.get('builds')
    if builds is not None and len(builds) > 0:
        builds.sort(cmp=compare)
        return builds[0]
    else:
        return None


def ask(url):
    try:
        request_url = urljoin(url + '/', 'api/json')
        response = urllib2.urlopen(request_url).read()
        return loads(response)
    except ValueError:
        print "Ignoring invalid job info at url %s" % url
    return {}


def notify(message):
    Popen(['notify-send', message])


def report_required(old_job_status, new_job_status, old_status_info):
    return old_job_status != new_job_status and old_status_info


def try_parse_config(config_location):
    try:
        with open(config_location) as config:
            return loads(config.read())
    except IOError as e:
        print e, "Proceeding without config"
    return {}


def configure_auth(config):
    if not 'jenkins url' in config:
        raise RuntimeError('Please specify jenkins URL in config, '
                           'use "jenkins url": "<URL to jenkins>"')

    if ('user' in config) and ('password' in config):
        opener = urllib2.build_opener()
        auth = '%s:%s' % (config['user'], config['password'])
        auth = base64.standard_b64encode(auth)
        opener.addheaders += [('Authorization', 'Basic ' + auth)]
        urllib2.install_opener(opener)


if __name__ == '__main__':
    if len(argv) < 2:
        print "Specify config location"
        exit(1)
    config = try_parse_config(argv[1])
    configure_auth(config)

    old_status_info = {}

    while True:
        notifications = []
        jobs = get_jobs(config)  # there may be new jobs
        new_status_info = jobs_running_info(jobs)
        for name, new_job_status in new_status_info.iteritems():
            old_job_status = old_status_info.get(name)
            if report_required(old_job_status, new_job_status,
                               old_status_info):
                notifications.append('Job %s is %s' % (name, new_job_status))
        if notifications:
            notify("\n".join(notifications))

        old_status_info = new_status_info
        sleep(5)
